### ISSUE TITLE
Implement the remove repository command

### ISSUE THREAD

**Issue by FerrisWasTaken** [Pax-Hub/paxy#14]
This should be implemented in the `rm_repo.rs` file. 
1. Check that the repository name is in the file
2. If yes, remove it. If not display an error message

**Comment by 0x177** [comment]
``rm_repo.rs`` does not exist. i am guessing  you mean ``paxy/src/actions/repository/uninstall.rs``

**Comment by 0x177** [comment]
``rm_repo.rs`` does not exist. do you mean ``/paxy/src/actions/repository/uninstall.rs``

**Comment by FerrisWasTaken** [comment]
Ah yes. It needs to be created at Paxy/src/actions/rm_repo.rs. as a side note we prefer the file name to match the associated command

**Comment by FerrisWasTaken** [comment]
Completed with [#16](https://github.com/Pax-Hub/paxy/pull/16)
